language: ruby
rvm:
  - 2.3.0
branches:
  only:
    - /^release-[\d.]*$/
    - release-candidate
    - master
services:
  - postgresql
before_script:
  - psql -c 'create database wonderreaderr_test;' -U postgres
