language: ruby
rvm:
  - 2.3.0
branches:
  only:
    - /^(?i:rc)-.*$/
    - release-candidate
    - master
services:
  - postgresql
before_script:
  - psql -c 'create database wonderreaderr_test;' -U postgres
