# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 295c2c4d005b57363139bd55063a902a844dc2483d65fc4314cb10685332332d124ad897e86b74223dba0e42c9dd77fd48fe1d5e61bf9f8728a0c7254bbe5361

rc:
  secret_key_base: 1af47704f399c2cc57e6a3e028c9a488d59b837fd06b56eea2b5ef72408c6a03b3511436166dd22635b535db78aecc10fab6a2e560bde13c8368c09bc98869b7

test:
  secret_key_base: 1f3cef2776698869d8fa6039608b7634f7db3d90b8333f4ec9341f6076832e4077f381b3f2155fcf23cf9864ed8ee39b536b3bc5ded5077c175ac37b0104ae4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
